"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, Check, Inbox as InboxIcon, LogOut, Menu, MessageCirclePlus, Mic, MoreVertical, Paperclip, Pencil, Plus, RefreshCw, Search, Send, Smile, Square, Tags, Trash2, UserRound, X } from "lucide-react";
import { api } from "@/lib/api";
import type { Agent, Conversation, Inbox, Label, Message } from "@/lib/types";

function payloadOf<T>(data: unknown): T[] {
  if (Array.isArray(data)) return data as T[];
  const object = data as { payload?: T[]; data?: { payload?: T[] } };
  return object?.payload || object?.data?.payload || [];
}
function timeLabel(value?: number) { return value ? new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value * 1000)) : ""; }
function durationLabel(seconds: number) { return `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`; }

export default function AtendimentoPage() {
  const router = useRouter();
  const fileInput = useRef<HTMLInputElement>(null), messagesEnd = useRef<HTMLDivElement>(null);
  const recorder = useRef<MediaRecorder | null>(null), recorderStream = useRef<MediaStream | null>(null), recorderChunks = useRef<Blob[]>([]), recordingTimer = useRef<number | null>(null);
  const [user, setUser] = useState<{ name: string; role: string } | null>(null);
  const [inboxes, setInboxes] = useState<Inbox[]>([]), [agents, setAgents] = useState<Agent[]>([]), [labels, setLabels] = useState<Label[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]), [selected, setSelected] = useState<Conversation | null>(null), [messages, setMessages] = useState<Message[]>([]);
  const [conversationLabels, setConversationLabels] = useState<string[]>([]), [labelFilter, setLabelFilter] = useState(""), [labelsOpen, setLabelsOpen] = useState(false);
  const [status, setStatus] = useState("open"), [inboxId, setInboxId] = useState<number | "">(""), [search, setSearch] = useState(""), [text, setText] = useState("");
  const [loading, setLoading] = useState(true), [sending, setSending] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const [newMode, setNewMode] = useState(false), [saveContact, setSaveContact] = useState(true), [newName, setNewName] = useState(""), [newPhone, setNewPhone] = useState(""), [newInbox, setNewInbox] = useState<number | "">(""), [newMessage, setNewMessage] = useState(""), [newSending, setNewSending] = useState(false);
  const [pendingFile, setPendingFile] = useState<File | null>(null), [pendingUrl, setPendingUrl] = useState(""), [mediaCaption, setMediaCaption] = useState("");
  const [labelManagerOpen, setLabelManagerOpen] = useState(false), [editingLabel, setEditingLabel] = useState<Label | null>(null), [labelTitle, setLabelTitle] = useState(""), [labelColor, setLabelColor] = useState("#00a884"), [labelDescription, setLabelDescription] = useState(""), [labelSaving, setLabelSaving] = useState(false);
  const [chatSearchOpen, setChatSearchOpen] = useState(false), [chatSearch, setChatSearch] = useState(""), [chatMenuOpen, setChatMenuOpen] = useState(false);
  const [recording, setRecording] = useState(false), [recordingSeconds, setRecordingSeconds] = useState(0), [audioBlob, setAudioBlob] = useState<Blob | null>(null), [audioUrl, setAudioUrl] = useState("");

  const logout = useCallback(() => { localStorage.removeItem("access_token"); router.replace("/login"); }, [router]);
  const loadConversations = useCallback(async () => { const params: Record<string, string | number> = { status }; if (inboxId) params.inbox_id = inboxId; const { data } = await api.get("/conversations", { params }); setConversations(payloadOf<Conversation>(data)); }, [status, inboxId]);
  const loadMessages = useCallback(async (id: number) => { const { data } = await api.get(`/conversations/${id}/messages`); setMessages(payloadOf<Message>(data)); }, []);
  const loadConversationLabels = useCallback(async (id: number) => { const { data } = await api.get(`/conversations/${id}/labels`); setConversationLabels(payloadOf<string>(data)); }, []);
  const loadLabels = useCallback(async () => { const { data } = await api.get("/labels"); setLabels(payloadOf<Label>(data)); }, []);

  useEffect(() => {
    if (!localStorage.getItem("access_token")) return router.replace("/login");
    Promise.all([api.get("/auth/me"), api.get("/inboxes"), api.get("/agents"), api.get("/labels")]).then(([me, boxes, team, tags]) => {
      setUser(me.data); setInboxes(payloadOf<Inbox>(boxes.data)); setAgents(payloadOf<Agent>(team.data)); setLabels(payloadOf<Label>(tags.data)); return loadConversations();
    }).catch((reason) => reason?.response?.status === 401 ? logout() : setError("Não foi possível carregar o atendimento.")).finally(() => setLoading(false));
  }, [loadConversations, logout, router]);
  useEffect(() => { loadConversations().catch(() => setError("Falha ao atualizar conversas.")); }, [loadConversations]);
  useEffect(() => { if (!selected) return; Promise.all([loadMessages(selected.id), loadConversationLabels(selected.id)]); const timer = window.setInterval(() => loadMessages(selected.id), 5000); return () => window.clearInterval(timer); }, [selected, loadMessages, loadConversationLabels]);
  useEffect(() => { messagesEnd.current?.scrollIntoView({ behavior: "smooth", block: "end" }); }, [messages]);
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]);
  useEffect(() => () => { if (pendingUrl) URL.revokeObjectURL(pendingUrl); }, [pendingUrl]);

  const filtered = useMemo(() => conversations.filter((c) => `${c.meta?.sender?.name || ""} ${c.meta?.sender?.phone_number || ""}`.toLowerCase().includes(search.toLowerCase()) && (!labelFilter || (c.labels || []).includes(labelFilter))), [conversations, search, labelFilter]);
  const visibleMessages = useMemo(() => messages.filter((m) => !chatSearch || (m.content || "").toLowerCase().includes(chatSearch.toLowerCase())), [messages, chatSearch]);
  const currentInbox = inboxes.find((item) => item.id === selected?.inbox_id);

  function resetAudio() { if (audioUrl) URL.revokeObjectURL(audioUrl); setAudioBlob(null); setAudioUrl(""); setRecordingSeconds(0); }
  function stopRecorderStream() { recorderStream.current?.getTracks().forEach((track) => track.stop()); recorderStream.current = null; if (recordingTimer.current) window.clearInterval(recordingTimer.current); recordingTimer.current = null; }
  async function startRecording() {
    if (!selected || selected.status === "resolved") return;
    if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) return setError("Este navegador não permite gravar áudio.");
    try {
      resetAudio(); const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mime = MediaRecorder.isTypeSupported("audio/webm;codecs=opus") ? "audio/webm;codecs=opus" : "audio/webm";
      const mediaRecorder = new MediaRecorder(stream, { mimeType: mime }); recorder.current = mediaRecorder; recorderStream.current = stream; recorderChunks.current = [];
      mediaRecorder.ondataavailable = (event) => { if (event.data.size) recorderChunks.current.push(event.data); };
      mediaRecorder.onstop = () => { const blob = new Blob(recorderChunks.current, { type: mime }); setAudioBlob(blob); setAudioUrl(URL.createObjectURL(blob)); stopRecorderStream(); };
      mediaRecorder.start(250); setRecording(true); setRecordingSeconds(0); recordingTimer.current = window.setInterval(() => setRecordingSeconds((value) => value + 1), 1000);
    } catch { setError("Permita o acesso ao microfone para gravar áudio."); stopRecorderStream(); }
  }
  function finishRecording() { if (recorder.current?.state === "recording") recorder.current.stop(); setRecording(false); }
  function cancelRecording() { if (recorder.current?.state === "recording") { recorder.current.onstop = null; recorder.current.stop(); } stopRecorderStream(); setRecording(false); resetAudio(); }

  async function sendMessage() {
    if (!selected || !text.trim() || selected.status === "resolved") return; setSending(true); setError("");
    try { await api.post(`/conversations/${selected.id}/messages`, { content: text.trim() }); setText(""); await Promise.all([loadMessages(selected.id), loadConversations()]); }
    catch (reason: any) { setError(reason?.response?.data?.detail || "Não foi possível enviar a mensagem."); } finally { setSending(false); }
  }
  function clearPendingFile() { if (pendingUrl) URL.revokeObjectURL(pendingUrl); setPendingFile(null); setPendingUrl(""); setMediaCaption(""); if (fileInput.current) fileInput.current.value = ""; }
  function chooseFile(file?: File) { if (!file) return; clearPendingFile(); setPendingFile(file); if (file.type.startsWith("image/") || file.type.startsWith("video/")) setPendingUrl(URL.createObjectURL(file)); }
  async function sendFile(file?: File, keepOnFailure = false, caption = "") {
    if (!selected || !file || selected.status === "resolved") return false; const form = new FormData(); form.append("attachment", file); form.append("caption", caption); setSending(true); setError("");
    try { await api.post(`/conversations/${selected.id}/attachments`, form); await loadMessages(selected.id); return true; }
    catch (reason: any) { setError(reason?.response?.data?.detail || "Não foi possível enviar o arquivo."); if (!keepOnFailure && fileInput.current) fileInput.current.value = ""; return false; }
    finally { setSending(false); if (fileInput.current) fileInput.current.value = ""; }
  }
  async function sendPendingFile() { if (pendingFile && await sendFile(pendingFile, true, mediaCaption)) { clearPendingFile(); setSuccess("Arquivo enviado com sucesso."); } }
  async function sendAudio() { if (!audioBlob) return; const ext = audioBlob.type.includes("ogg") ? "ogg" : "webm"; const file = new File([audioBlob], `audio-${Date.now()}.${ext}`, { type: audioBlob.type }); if (await sendFile(file, true)) { resetAudio(); setSuccess("Áudio enviado com sucesso."); } }
  async function changeStatus(next: string) {
    if (!selected) return; if (next === "resolved" && !window.confirm("Arquivar esta conversa? Ela voltará se o cliente enviar uma nova mensagem.")) return; setSending(true);
    try { await api.post(`/conversations/${selected.id}/status`, { status: next }); setSuccess(next === "resolved" ? "Conversa arquivada." : "Conversa reaberta."); setSelected(null); setMessages([]); setConversationLabels([]); await loadConversations(); } finally { setSending(false); }
  }
  async function assign(value: string) { if (!selected) return; await api.post(`/conversations/${selected.id}/assignment`, { assignee_id: value ? Number(value) : null }); await loadConversations(); }
  async function toggleLabel(title: string) {
    if (!selected) return; const previous = conversationLabels; const next = previous.includes(title) ? previous.filter((item) => item !== title) : [...previous, title]; setConversationLabels(next);
    try { await api.post(`/conversations/${selected.id}/labels`, { labels: next }); setConversations((items) => items.map((item) => item.id === selected.id ? { ...item, labels: next } : item)); }
    catch { setConversationLabels(previous); setError("Não foi possível atualizar as etiquetas."); }
  }
  async function createNewConversation(event: React.FormEvent) {
    event.preventDefault(); if (!newInbox) return; setNewSending(true); setError("");
    try { const displayName = saveContact && newName.trim() ? newName.trim() : newPhone.replace(/\D/g, ""); const { data } = await api.post("/conversations/new", { name: displayName, phone_number: newPhone, inbox_id: newInbox, message: newMessage.trim() }); setSuccess(data?.mensagem || "Mensagem enviada com sucesso."); setNewMode(false); setNewName(""); setNewPhone(""); setNewInbox(""); setNewMessage(""); setSearch(""); await loadConversations(); }
    catch (reason: any) { setError(reason?.response?.data?.detail || "Não foi possível iniciar a conversa."); } finally { setNewSending(false); }
  }
  function beginNewConversation(phone = "") { setSelected(null); setNewMode(true); setNewPhone(phone.replace(/\D/g, "")); setNewInbox(inboxId || inboxes[0]?.id || ""); setNewMessage(""); setNewName(""); }
  function editLabel(label?: Label) { setEditingLabel(label || null); setLabelTitle(label?.title || ""); setLabelColor(label?.color || "#00a884"); setLabelDescription(label?.description || ""); }
  async function saveLabel(event: React.FormEvent) { event.preventDefault(); setLabelSaving(true); try { const body = { title: labelTitle.trim(), color: labelColor, description: labelDescription.trim() }; if (editingLabel?.id) await api.patch(`/labels/${editingLabel.id}`, body); else await api.post("/labels", body); await loadLabels(); editLabel(); setSuccess(editingLabel ? "Etiqueta atualizada." : "Etiqueta criada."); } catch (reason: any) { setError(reason?.response?.data?.detail || "Não foi possível salvar a etiqueta."); } finally { setLabelSaving(false); } }
  async function removeLabel(label: Label) { if (!label.id || !window.confirm(`Excluir a etiqueta “${label.title}”?`)) return; try { await api.delete(`/labels/${label.id}`); await loadLabels(); setSuccess("Etiqueta excluída."); } catch (reason: any) { setError(reason?.response?.data?.detail || "Não foi possível excluir a etiqueta."); } }
  if (loading) return <main className="screen-center">Carregando atendimento...</main>;

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="sidebar-brand"><div className="brand-mark small">N</div><div><strong>Central Nhora</strong><span>Atendimento e operações</span></div></div>
      <nav><button className={!inboxId && !labelFilter && !newMode ? "nav-active" : ""} onClick={() => {setInboxId("");setLabelFilter("");setNewMode(false)}}><Menu size={20}/><span>Todas as conversas</span></button><div className="nav-section-title"><InboxIcon size={15}/> Filas</div><div className="sidebar-queues">{inboxes.map((item) => <button key={item.id} className={inboxId === item.id && !newMode ? "nav-active" : ""} onClick={() => {setInboxId(item.id);setLabelFilter("");setNewMode(false)}}><span className={`queue-dot ${item.department || "geral"}`}/><span>{item.display_name || item.name}</span></button>)}</div><button className={newMode ? "nav-active" : ""} onClick={() => beginNewConversation(search)}><MessageCirclePlus size={20}/><span>Nova conversa</span></button><div className="nav-divider"/><div className="nav-section-title"><Tags size={15}/> Etiquetas <button className="manage-labels-button" title="Criar e editar etiquetas" onClick={() => {editLabel();setLabelManagerOpen(true)}}><Plus size={15}/></button></div><div className="sidebar-labels">{labels.map((label) => <button key={label.title} className={labelFilter === label.title ? "nav-active" : ""} onClick={() => {setLabelFilter(label.title);setNewMode(false)}}><span className="label-dot" style={{background: label.color || "#64748b"}}/><span>{label.title}</span></button>)}{!labels.length && <small>Nenhuma etiqueta cadastrada</small>}</div></nav>
      <div className="sidebar-user"><div className="profile-avatar">{user?.name?.slice(0,1).toUpperCase() || "O"}</div><div className="profile-copy"><strong>{user?.name}</strong><span>{user?.role}</span></div><button title="Sair" onClick={logout}><LogOut size={19}/></button></div>
    </aside>
    <section className="conversation-list">
      <header><div><h1>{newMode ? "Nova conversa" : labelFilter || "Conversas"}</h1>{labelFilter && !newMode && <small>Conversas com esta etiqueta</small>}</div><div className="list-actions"><button title="Nova conversa" onClick={() => beginNewConversation(search)}><MessageCirclePlus size={21}/></button><button title="Atualizar" onClick={loadConversations}><RefreshCw size={20}/></button></div></header>
      <div className="filters"><div className="search"><Search size={17}/><input placeholder="Buscar contato..." value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="filter-chips"><button className={status === "open" ? "chip-active" : ""} onClick={() => setStatus("open")}>Abertas</button><button className={status === "pending" ? "chip-active" : ""} onClick={() => setStatus("pending")}>Pendentes</button><button className={status === "resolved" ? "chip-active" : ""} onClick={() => setStatus("resolved")}>Arquivadas</button><select value={inboxId} onChange={(e) => setInboxId(e.target.value ? Number(e.target.value) : "")}><option value="">Todas as caixas</option>{inboxes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div>
      <div className="conversation-scroll">{/^\D*\d[\d\s()+-]{8,}$/.test(search) && !filtered.some(c => (c.meta?.sender?.phone_number || "").replace(/\D/g, "").includes(search.replace(/\D/g, ""))) && <button className="start-number" onClick={() => beginNewConversation(search)}><div className="avatar"><MessageCirclePlus size={22}/></div><div><strong>Conversar com {search}</strong><span>Número ainda não aparece nas conversas</span></div></button>}{filtered.map((conversation) => { const contact = conversation.meta?.sender; return <button key={conversation.id} className={`conversation-item ${selected?.id === conversation.id ? "selected" : ""}`} onClick={() => { setNewMode(false); setSelected(conversation); resetAudio(); clearPendingFile(); setChatSearch(""); setChatSearchOpen(false); setChatMenuOpen(false); setLabelsOpen(false); }}><div className="avatar">{contact?.thumbnail ? <img src={contact.thumbnail} alt=""/> : <UserRound size={21}/>}</div><div className="conversation-copy"><div><strong>{contact?.name || "Contato"}</strong><time>{timeLabel(conversation.last_activity_at || conversation.timestamp)}</time></div><p>{conversation.last_non_activity_message?.content || contact?.phone_number || "Sem mensagem"}</p>{conversation.labels?.length ? <div className="mini-labels">{conversation.labels.slice(0,2).map((item) => <span key={item}>{item}</span>)}</div> : null}</div>{conversation.unread_count > 0 && <span className="unread">{conversation.unread_count}</span>}</button>; })}{!filtered.length && !search && <div className="empty-list">Nenhuma conversa encontrada.</div>}</div>
    </section>
    <section className="chat-panel">{newMode ? <div className="new-chat-screen"><header><button onClick={() => setNewMode(false)}><X size={21}/></button><div><strong>Nova conversa</strong><span>Inicie um atendimento pelo WhatsApp</span></div></header><form onSubmit={createNewConversation}><div className="new-chat-hero"><div className="avatar"><UserRound size={26}/></div><div><strong>{saveContact && newName.trim() ? newName : newPhone || "Novo contato"}</strong><span>O número será validado antes do envio</span></div></div><label>Telefone com DDD</label><input autoFocus value={newPhone} onChange={e => setNewPhone(e.target.value)} inputMode="numeric" placeholder="Ex.: 62999887766" required/><label>Enviar por</label><select value={newInbox} onChange={e => setNewInbox(e.target.value ? Number(e.target.value) : "")} required><option value="">Selecione a caixa</option>{inboxes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="save-contact"><input type="checkbox" checked={saveContact} onChange={e => setSaveContact(e.target.checked)}/><span>Salvar contato com um nome</span></label>{saveContact && <input value={newName} onChange={e => setNewName(e.target.value)} placeholder="Nome do cliente" required/>}<label>Primeira mensagem</label><textarea value={newMessage} onChange={e => setNewMessage(e.target.value)} placeholder="Digite a mensagem" required/><div className="new-chat-actions"><button type="button" onClick={() => setNewMode(false)}>Cancelar</button><button type="submit" disabled={newSending}><Send size={18}/>{newSending ? "Enviando..." : "Enviar mensagem"}</button></div></form></div> : selected ? <>
      <header className="chat-header"><div className="avatar">{selected.meta?.sender?.thumbnail ? <img src={selected.meta.sender.thumbnail} alt=""/> : <UserRound size={21}/>}</div><div className="chat-contact"><strong>{selected.meta?.sender?.name || "Contato"}</strong><span>{selected.meta?.sender?.phone_number}</span><small><InboxIcon size={12}/> Enviando por: {currentInbox?.name || `Caixa ${selected.inbox_id}`}</small></div><div className="chat-actions"><select value={selected.meta?.assignee?.id || ""} onChange={(e) => assign(e.target.value)}><option value="">Sem responsável</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><div className="labels-wrap"><button className={`header-icon ${labelsOpen ? "button-active" : ""}`} title="Etiquetas" onClick={() => setLabelsOpen(v => !v)}><Tags size={20}/></button>{labelsOpen && <div className="labels-popover"><div><strong>Etiquetas</strong><button onClick={() => setLabelsOpen(false)}><X size={17}/></button></div>{labels.map((label) => <button key={label.title} onClick={() => toggleLabel(label.title)}><span className="label-dot" style={{background: label.color || "#64748b"}}/><span>{label.title}</span>{conversationLabels.includes(label.title) && <Check size={17}/>}</button>)}</div>}</div><button className="resolve-button" title={selected.status === "resolved" ? "Reabrir" : "Arquivar"} onClick={() => changeStatus(selected.status === "resolved" ? "open" : "resolved")}><Archive size={20}/></button><button className={`header-icon ${chatSearchOpen ? "button-active" : ""}`} title="Pesquisar" onClick={() => setChatSearchOpen(v => !v)}><Search size={20}/></button><div className="chat-menu-wrap"><button className={`header-icon ${chatMenuOpen ? "button-active" : ""}`} onClick={() => setChatMenuOpen(v => !v)}><MoreVertical size={21}/></button>{chatMenuOpen && <div className="chat-menu"><button onClick={() => changeStatus(selected.status === "resolved" ? "open" : "resolved")}>{selected.status === "resolved" ? "Reabrir conversa" : "Arquivar conversa"}</button><button onClick={() => {setLabelsOpen(true);setChatMenuOpen(false)}}>Gerenciar etiquetas</button><button onClick={() => {setChatSearchOpen(true);setChatMenuOpen(false)}}>Pesquisar mensagens</button></div>}</div></div></header>
      {(conversationLabels.length > 0 || Object.keys(selected.custom_attributes || {}).length > 0) && <div className="conversation-context">{conversationLabels.map((title) => { const label = labels.find(item => item.title === title); return <button key={title} onClick={() => toggleLabel(title)}><span className="label-dot" style={{background: label?.color || "#64748b"}}/>{title}<X size={12}/></button>})}{Object.entries(selected.custom_attributes || {}).filter(([, value]) => value !== null && value !== "").slice(0, 8).map(([key, value]) => <span key={key}><b>{key.replaceAll("_", " ")}:</b> {String(value)}</span>)}</div>}
      {chatSearchOpen && <div className="chat-search"><Search size={17}/><input autoFocus value={chatSearch} onChange={e => setChatSearch(e.target.value)} placeholder="Pesquisar mensagens nesta conversa"/><button onClick={() => {setChatSearchOpen(false);setChatSearch("")}}>×</button></div>}
      <div className="messages">{visibleMessages.map((message) => { const outgoing = message.message_type === 1 || message.message_type === "outgoing"; return <div key={message.id} className={`message-row ${outgoing ? "outgoing" : "incoming"}`}><div className="bubble">{message.content && <p>{message.content}</p>}{message.attachments?.map((file) => file.file_type === "image" ? <a key={file.id} href={file.data_url} target="_blank"><img className="message-image" src={file.thumb_url || file.data_url} alt="Imagem"/></a> : file.file_type === "video" ? <video key={file.id} className="message-video" controls playsInline preload="metadata" poster={file.thumb_url} src={file.data_url}>Seu navegador não consegue reproduzir este vídeo.</video> : file.file_type === "audio" ? <audio key={file.id} className="message-audio" controls preload="metadata" src={file.data_url}/> : <a key={file.id} className="attachment" href={file.data_url} target="_blank">Abrir anexo</a>)}<time>{timeLabel(message.created_at)}</time></div></div>})}<div ref={messagesEnd}/></div>
      {selected.status === "resolved" ? <footer className="archived-composer"><Archive size={19}/><span>Esta conversa está arquivada.</span><button onClick={() => changeStatus("open")}>Reabrir atendimento</button></footer> : pendingFile ? <footer className="media-preview"><div className="media-preview-top"><strong>Prévia do anexo</strong><button title="Cancelar" onClick={clearPendingFile}><X size={21}/></button></div><div className="media-preview-body">{pendingFile.type.startsWith("image/") && <img src={pendingUrl} alt="Prévia"/>}{pendingFile.type.startsWith("video/") && <video src={pendingUrl} controls playsInline/>}{!pendingUrl && <div className="document-preview"><Paperclip size={28}/><strong>{pendingFile.name}</strong><span>{Math.ceil(pendingFile.size / 1024)} KB</span></div>}</div><div className="media-preview-caption"><input value={mediaCaption} onChange={e => setMediaCaption(e.target.value)} placeholder="Adicionar legenda (opcional)"/><button disabled={sending} onClick={sendPendingFile}><Send size={20}/></button></div></footer> : <footer className={`composer ${recording || audioBlob ? "audio-mode" : ""}`}><input ref={fileInput} hidden type="file" accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={(e) => chooseFile(e.target.files?.[0])}/>{recording ? <div className="recording-bar"><button title="Cancelar" onClick={cancelRecording}><Trash2 size={21}/></button><span className="recording-dot"/><strong>{durationLabel(recordingSeconds)}</strong><span>Gravando áudio...</span><button className="stop-recording" title="Parar" onClick={finishRecording}><Square size={18}/></button></div> : audioBlob ? <div className="audio-preview"><button title="Excluir" onClick={resetAudio}><Trash2 size={21}/></button><audio controls src={audioUrl}/><button className="send-audio" disabled={sending} title="Enviar" onClick={sendAudio}><Send size={21}/></button></div> : <><button className="icon-button" title="Emoji"><Smile size={23}/></button><button className="icon-button" title="Anexar imagem, vídeo ou documento" onClick={() => fileInput.current?.click()}><Paperclip size={22}/></button><textarea placeholder="Digite uma mensagem" value={text} onChange={e => setText(e.target.value)} onKeyDown={e => {if(e.key === "Enter" && !e.shiftKey){e.preventDefault();sendMessage()}}}/>{text.trim() ? <button className="send-button" disabled={sending} onClick={sendMessage}><Send size={21}/></button> : <button className="send-button" disabled={sending} title="Gravar áudio" onClick={startRecording}><Mic size={23}/></button>}</>}</footer>}
    </> : <div className="empty-chat"><div className="whatsapp-symbol">N</div><h2>Central Nhora</h2><p>Leads, campanhas internas, suporte e mensagens transacionais com o contexto preservado.</p><span>Selecione uma conversa para começar</span></div>}</section>
    {labelManagerOpen && <div className="modal-backdrop" onMouseDown={() => setLabelManagerOpen(false)}><div className="label-manager" onMouseDown={e => e.stopPropagation()}><div className="modal-heading"><div><h2>Organizar etiquetas</h2><p>Crie, renomeie, altere a cor ou exclua etiquetas.</p></div><button onClick={() => setLabelManagerOpen(false)}>×</button></div><div className="label-manager-grid"><div className="label-manager-list"><button className="new-label-button" onClick={() => editLabel()}><Plus size={17}/> Nova etiqueta</button>{labels.map(label => <div key={label.id || label.title}><span className="label-dot" style={{background: label.color || "#64748b"}}/><strong>{label.title}</strong><button title="Editar" onClick={() => editLabel(label)}><Pencil size={15}/></button><button title="Excluir" onClick={() => removeLabel(label)}><Trash2 size={15}/></button></div>)}</div><form onSubmit={saveLabel}><label>Nome da etiqueta</label><input value={labelTitle} onChange={e => setLabelTitle(e.target.value)} placeholder="Ex.: Aguardando documentos" required/><label>Cor</label><div className="color-field"><input type="color" value={labelColor} onChange={e => setLabelColor(e.target.value)}/><span>{labelColor}</span></div><label>Descrição <span>opcional</span></label><textarea value={labelDescription} onChange={e => setLabelDescription(e.target.value)} placeholder="Quando esta etiqueta deve ser usada?"/><div className="modal-actions"><button type="button" className="cancel-button" onClick={() => editLabel()}>Limpar</button><button type="submit" className="primary-button" disabled={labelSaving}>{labelSaving ? "Salvando..." : editingLabel ? "Salvar alterações" : "Criar etiqueta"}</button></div></form></div></div></div>}
    {error && <div className="toast-error" onClick={() => setError("")}>{error}</div>}{success && <div className="toast-success" onClick={() => setSuccess("")}>{success}</div>}
  </main>;
}
